### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by mvasin** [shrinerb/shrine-tus-demo#2]
Janko, can you please add some tests, to give an idea on how would you approach to testing such an application? I'm interested in higher level, functional/integration testing.

**Comment by janko** [comment]
@mvasin Yeah, it would be nice to have high-level tests for this, and I agree that it's an interesting problem how to test this, though I'm afraid I don't have the time to write them.

The main difficulty I think is that in order to test resumability the upload has to take some time, which is hard to re-create in tests. I would definitely try to expose the `tus.Upload` JavaScript instance so that it can be manipulated in tests (Capybara's JavaScript drivers can execute custom JavaScript at any point), you can then call `tus.Upload#start()` and `tus.Upload#abort()`, though I don't know how to make sure that the upload hasn't already finished before you had the chance to call `tus.Upload#abort()` and inspect things like the progress bar and then `tus.Upload#start()` to test resumability.

If you have time to figure it out and add tests, that would be greatly appreciated.

**Comment by mvasin** [comment]
Maybe there is a way to programmatically limit bandwidth, so we'll be sure a file wasn't uploaded yet. Or stop somewhere in between chunks. It's just a blind guess.

Given my small experience in writing tests and my huge wish to learn how to do it, I think I'll write it, but it will take quite a while (a few months).

**Comment by janko** [comment]
After some more thinking, I think that writing tests for resumability of uploads would be an overkill. I would write tests only for the basic file upload functionality, and any checking of resumability I would do manually. Therefore I don't think it makes sense to include tests for this demo.
