### ISSUE TITLE
Aws::S3::Errors::NoSuchKey when both tus and Shrine storages are on S3

### ISSUE THREAD

**Issue by mvasin** [shrinerb/shrine-tus-demo#4]
I forked this repo and [created a branch](https://github.com/mvasin/shrine-tus-demo/tree/tus-s3-storage-s3), where I carefully reproduced instructions for case when tus-server and Shrine are both on S3 (optimized version, with file id substitution in Roda tree).

The problem is: if I upload a file, then delete it, then upload the same file once again, I get

```
E, [2017-04-09T16:24:25.469177 #524] ERROR -- : Sucker Punch job error for class: 'PromoteJob' args: [{"attachment"=>"{\"storage\":\"cache\",\"id\":\"b711b7274ee5f8539107b51a975b78db\",\"metadata\":{\"filename\":\"18-jquery-ujs-callbacks.mp4\",\"size\":22467168,\"mime_type\":\"video/mp4\"}}", "record"=>["Movie", "2"], "name"=>"video", "shrine_class"=>"VideoUploader", "action"=>"store", "phase"=>"store"}]
Aws::S3::Errors::NoSuchKey The specified key does not exist.
```

Here are the details. I start with clean S3 bucket and clean postgresql, then upload one file. It gets promoted:

```
mvasin$ aws s3 ls s3://ntv.test --recursive
2017-04-09 19:18:35   22467168 store/64f4170bddc1ac17d5a0a2dc66eadf7c.mp4
2017-04-09 19:18:26        244 tus/b711b7274ee5f8539107b51a975b78db.info
```

Then I delete this file (from within Roda app). S3 looks like this:

```
mvasin$ aws s3 ls s3://ntv.test --recursive
2017-04-09 19:18:26        244 tus/b711b7274ee5f8539107b51a975b78db.info
```

No problems (yet). 

Then I upload the same file once again, progress bar runs till the end, no errors in browser's JS console. But S3 looks like nothing was uploaded:

```
mvasin$ aws s3 ls s3://ntv.test --recursive
2017-04-09 19:18:26        244 tus/b711b7274ee5f8539107b51a975b78db.info
```

I hit 'Submit' and get `Aws::S3::Errors::NoSuchKey` above in error in Roda logs. S3 looks the same (just .info file), and, of course, there is a 404 error for ` https://s3-eu-west-1.amazonaws.com/ntv.test/tus/b711b7274ee5f8539107b51a975…Signature=02866c55e4d48eb0ce7dde941b73e4c12eb40c25689c4f1be8f00301c0b3fddf` file at `http://localhost:9292/movies`.

**Comment by janko** [comment]
Thank you for the detailed report, I know what is the issue.

The tus-ruby-server saves uploaded files as two S3 objects, once is on key `<uid>` and holds file content, the other one is on key `<uid>.info` which holds file info (it's not possible to use `:metadata` for storing the file info on the main object, because S3 objects are immutable, so file info wouldn't be updatable, which is mandatory for the tus protocol).

When the browser makes a HEAD request to the `tus-ruby-server` to ask it whether the file still exists (one the beginning of the upload), the S3 storage on the `tus-ruby-server` checks for the existence of the `<uid>.info` file info S3 object. However, Shrine knows only about the `<uid>` file S3 object, and it will delete only that file after it's promoted to permanent location (because `delete_promoted` plugin is loaded).

Now when browser makes another HEAD request to check whether the file exists, `tus-ruby-sever` will return true because the `<uid>.info` object still exists (while `<uid>` one was deleted). Checking additionally whether the `<uid>` object exists would incur a performance penalty of an additional HTTP request to `tus-ruby-server`, so I would prefer to avoid it.

My best solution is to remove the `delete_promoted` plugin which deletes the tus file (and discourage it in the README), which is fine because there should be a recurring task that deletes exired files from `tus-ruby-server` anyway, as noted in the `tus-ruby-server` README. Would that be feasible for you?

**Comment by mvasin** [comment]
Thanks for quick response! That seems alright, I'll remove `delete_promoted ` in my setup.
Please mention this situation in readme and close the issue.

**Comment by janko** [comment]
Removed the `delete_promoted` plugin and discouraged it in the README in latest commits, closing this then.
