### ISSUE TITLE
Timeout when updating attachment data

### ISSUE THREAD

**Issue by tfwright** [shrinerb/shrine-tus-demo#5]
Hi,

Thanks for all your work on these gems. 

I am following this demo to try to get shrine working with tus on Rails with s3 storage. 

```
gem 'shrine', "~> 2.8.0"
gem 'shrine-tus', "~> 1.1.0"
gem 'tus-server', "~> 2.0.2"
```

However, I am getting the following error when posting the attachment data, after a long delay, suggesting in fact it is timing out trying to download the attachment from the tus server:

```
18:03:25 web.1       | timed out while reading data excluded from capture: Not configured to send/capture in environment 'development'
18:03:25 web.1       |   
18:03:25 web.1       | Down::TimeoutError (timed out while reading data):
18:03:25 web.1       |   
18:03:25 web.1       | down (4.2.1) lib/down/net_http.rb:251:in `request_error!'
18:03:25 web.1       | down (4.2.1) lib/down/net_http.rb:169:in `rescue in net_http_request'
18:03:25 web.1       | down (4.2.1) lib/down/net_http.rb:159:in `net_http_request'
18:03:25 web.1       | down (4.2.1) lib/down/net_http.rb:82:in `block in open'
```

Here is an example of the attachment data I'm posting:

```
{"id":"http://ocalhost:5000/[...]/ecd34e90ba03b1415db65e382dc87727","storage":"cache","metadata":{"filename":"file.pdf","mime_type":"application/pdf","size":1289}}

```

When I copy and paste that URL in my browser, the file downloads just fine. 

Here are what I think are the relative parts of my shrine config:

```
Tus::Server.opts[:storage] = Tus::Storage::S3.new(prefix: "tus", **s3_options)

  Shrine.storages = {
    local_cache: Shrine::Storage::FileSystem.new('public', prefix: "uploads/#{Rails.env}/"),
    cache: Shrine::Storage::S3.new(prefix: 'cache', **s3_options), 
    store: Shrine::Storage::S3.new(prefix: 'store', **s3_options),
    tus:   Shrine::Storage::Tus.new
  }
```

These configs were working fine before adding the tus store.

Any insight you can give would be greatly appreciated!

**Comment by janko** [comment]
Thank you for reporting this.

The default Net::HTTP timeout is 60 seconds, so it's definitely not too little. Could you try switching the downloader to the HTTP.rb gem, and see if you get the same error? You can do it by adding

```rb
gem "http", "~> 3.0"
```

to the Gemfile and telling `Shrine::Storage::Tus` to use the `:http` downloader:

```rb
Shrine::Storage::Tus.new(downloader: :http)
```

**Comment by tfwright** [comment]
Thanks for replying so quickly.

I tried what you suggested and now it doesn't timeout, but it appears to just hang, never completing the request. this was the last console message printed by Rails: `18:33:24 web.1       |    (0.4ms)  BEGIN`

**Comment by janko** [comment]
Ok, I expected that, because the HTTP.rb backend doesn't come with a default timeout. I just wanted to check that it wasn't a Net::HTTP-specific problem.

I'm unfortunately not able to reproduce the problem; when I swap `FileSystem` storage for `S3` in this demo app, promoting from cache to store works just fine, the file is successfully downloaded from the tus server and uploaded to S3.

It's very odd that in your case the download times out when `Shrine::Storage::Tus` is used (which uses `Down`), but it successfully completes when downloading through the browser. Are you running the tus server on Goliath or Puma? How large is the file you're testing with?

**Comment by tfwright** [comment]
The file is only about a 1 KB. I should've mentioned in my original post that I am mounting the tus server in Rails like so: `mount Tus::Server => "/endpoint"`

Previous to this change, I was using the upload endpoint plugin which required mounting the uploader class for the attachment. I was using the same endpoint.

To be clear, I am definitely able to upload and download from that endpoint. It's just shrine that seems to timeout.

**Comment by janko** [comment]
Is it possible that your web server configuration is allowing only a single request at a time? If that's the case, then initiating a request from another request will necessarily hang, because the web server is waiting for the first request to finish. This happened to me once in the past, and took me a while to figure out what's going on. Make sure you configured your Puma/Unicorn to run more than one worker.

If that's not the case either, I would need you to create a new fresh Rails app that reproduces the issue and share it with me.

**Comment by tfwright** [comment]
I changed my Puma config to use 2 workers and that fixed my issue. Thanks for your help!

🥇
